version: '3.7'
services:
  htmlspitter:
    build: https://github.com/qdm12/htmlspitter.git
    image: qmcgaw/htmlspitter
    container_name: htmlspitter
    network_mode: bridge
    init: true
    # security_opt:
    #   - seccomp=./chrome.json
    ports:
      - 8000:8000/tcp
    environment:
      - MAX_PAGES=
      - MAX_HITS=
      - MAX_AGE_UNUSED=
      - MAX_BROWSERS=
      - MAX_CACHE_SIZE=
      - MAX_QUEUE_SIZE=
      - LOG=
      - TIMEOUT=
    restart: always